### ISSUE TITLE
Color selection indicator

### ISSUE THREAD

**Issue by soareseneves** [dmrschmidt/SwiftColorWheel#2]
Hello,

I was wondering if you could add some sort of color selection indicator like this android library: https://github.com/QuadFlask/colorpicker/blob/master/screenshot/screenshot3.png
https://github.com/QuadFlask/colorpicker/blob/master/screenshot/screenshot.png

https://github.com/QuadFlask/colorpicker

Thank you.

**Comment by dmrschmidt** [comment]
I'll definitely consider adding this. Thanks for the suggestion!

**Comment by dmrschmidt** [comment]
Just added this and released 1.5.0. Swift Package Manager is now also supported.
